"""new fields in post  model

Revision ID: 28d73975ac59
Revises: 1ddcd269ff47
Create Date: 2022-01-31 13:10:58.363983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d73975ac59'
down_revision = '1ddcd269ff47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body2', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body2')
    # ### end Alembic commands ###
