"""post body3

Revision ID: 8b60a5dee790
Revises: cce8fd357ffa
Create Date: 2022-01-31 16:20:26.183223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b60a5dee790'
down_revision = 'cce8fd357ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body1', sa.String(length=140), nullable=True))
    op.add_column('post', sa.Column('body4', sa.String(length=140), nullable=True))
    op.drop_column('post', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('post', 'body4')
    op.drop_column('post', 'body1')
    # ### end Alembic commands ###
