"""added profile pict

Revision ID: d03756b7815b
Revises: 845e6def5277
Create Date: 2022-03-02 16:17:18.286475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03756b7815b'
down_revision = '845e6def5277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('u_pict', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_u_pict'), 'user', ['u_pict'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_u_pict'), table_name='user')
    op.drop_column('user', 'u_pict')
    # ### end Alembic commands ###
